syntax = "proto3";

package auth.v1;

option go_package = "github.com/role-play-dev/contracts/gen/auth/v1;authv1";

service AuthService {
    rpc CredentialsRegisterLinkSend(CredentialsRegisterLinkSendRequest) returns (CredentialsRegisterLinkSendResponce) {}
    rpc CredentialsRegisterLinkConfirm(CredentialsRegisterLinkConfirmRequest) returns (CredentialsRegisterLinkConfirmResponce) {}
    rpc CredentialsLogin(CredentialsLoginRequest) returns (CredentialsLoginResponce) {}
    rpc TokenRefresh(TokenRefreshRequest) returns (TokenRefreshResponce) {}
}

message CredentialsRegisterLinkSendRequest {
    string client_address = 1;
    string email = 2;    
}

message CredentialsRegisterLinkSendResponce {
}

message CredentialsRegisterLinkConfirmRequest {
    string auth_token = 1;
    string username = 2;
    string password = 3;
}

message CredentialsRegisterLinkConfirmResponce {

}

message CredentialsLoginRequest {
    string username = 1;
    string password = 2;
}

message CredentialsLoginResponce {
    string access_token = 1;
    string refresh_token = 2;
}

message TokenRefreshRequest {
    string refresh_token = 1;
}

message TokenRefreshResponce {
    string access_token = 1;
    string refresh_token = 2;
}

