// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialsRegisterLinkSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientAddress string                 `protobuf:"bytes,1,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRegisterLinkSendRequest) Reset() {
	*x = CredentialsRegisterLinkSendRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRegisterLinkSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRegisterLinkSendRequest) ProtoMessage() {}

func (x *CredentialsRegisterLinkSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRegisterLinkSendRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRegisterLinkSendRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsRegisterLinkSendRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *CredentialsRegisterLinkSendRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CredentialsRegisterLinkSendResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRegisterLinkSendResponce) Reset() {
	*x = CredentialsRegisterLinkSendResponce{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRegisterLinkSendResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRegisterLinkSendResponce) ProtoMessage() {}

func (x *CredentialsRegisterLinkSendResponce) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRegisterLinkSendResponce.ProtoReflect.Descriptor instead.
func (*CredentialsRegisterLinkSendResponce) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

type CredentialsRegisterLinkConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRegisterLinkConfirmRequest) Reset() {
	*x = CredentialsRegisterLinkConfirmRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRegisterLinkConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRegisterLinkConfirmRequest) ProtoMessage() {}

func (x *CredentialsRegisterLinkConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRegisterLinkConfirmRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRegisterLinkConfirmRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialsRegisterLinkConfirmRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *CredentialsRegisterLinkConfirmRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CredentialsRegisterLinkConfirmRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CredentialsRegisterLinkConfirmResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRegisterLinkConfirmResponce) Reset() {
	*x = CredentialsRegisterLinkConfirmResponce{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRegisterLinkConfirmResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRegisterLinkConfirmResponce) ProtoMessage() {}

func (x *CredentialsRegisterLinkConfirmResponce) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRegisterLinkConfirmResponce.ProtoReflect.Descriptor instead.
func (*CredentialsRegisterLinkConfirmResponce) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

type CredentialsLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsLoginRequest) Reset() {
	*x = CredentialsLoginRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsLoginRequest) ProtoMessage() {}

func (x *CredentialsLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsLoginRequest.ProtoReflect.Descriptor instead.
func (*CredentialsLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialsLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CredentialsLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CredentialsLoginResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsLoginResponce) Reset() {
	*x = CredentialsLoginResponce{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsLoginResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsLoginResponce) ProtoMessage() {}

func (x *CredentialsLoginResponce) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsLoginResponce.ProtoReflect.Descriptor instead.
func (*CredentialsLoginResponce) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialsLoginResponce) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CredentialsLoginResponce) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRefreshRequest) Reset() {
	*x = TokenRefreshRequest{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefreshRequest) ProtoMessage() {}

func (x *TokenRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefreshRequest.ProtoReflect.Descriptor instead.
func (*TokenRefreshRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *TokenRefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenRefreshResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRefreshResponce) Reset() {
	*x = TokenRefreshResponce{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefreshResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefreshResponce) ProtoMessage() {}

func (x *TokenRefreshResponce) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefreshResponce.ProtoReflect.Descriptor instead.
func (*TokenRefreshResponce) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *TokenRefreshResponce) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenRefreshResponce) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x06authpb\"a\n" +
	"\"CredentialsRegisterLinkSendRequest\x12%\n" +
	"\x0eclient_address\x18\x01 \x01(\tR\rclientAddress\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"%\n" +
	"#CredentialsRegisterLinkSendResponce\"~\n" +
	"%CredentialsRegisterLinkConfirmRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"(\n" +
	"&CredentialsRegisterLinkConfirmResponce\"Q\n" +
	"\x17CredentialsLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"b\n" +
	"\x18CredentialsLoginResponce\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\":\n" +
	"\x13TokenRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14TokenRefreshResponce\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken2\xb1\x03\n" +
	"\vAuthService\x12x\n" +
	"\x1bCredentialsRegisterLinkSend\x12*.authpb.CredentialsRegisterLinkSendRequest\x1a+.authpb.CredentialsRegisterLinkSendResponce\"\x00\x12\x81\x01\n" +
	"\x1eCredentialsRegisterLinkConfirm\x12-.authpb.CredentialsRegisterLinkConfirmRequest\x1a..authpb.CredentialsRegisterLinkConfirmResponce\"\x00\x12W\n" +
	"\x10CredentialsLogin\x12\x1f.authpb.CredentialsLoginRequest\x1a .authpb.CredentialsLoginResponce\"\x00\x12K\n" +
	"\fTokenRefresh\x12\x1b.authpb.TokenRefreshRequest\x1a\x1c.authpb.TokenRefreshResponce\"\x00B+Z)github.com/role-play-dev/contarcts/authpbb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_proto_goTypes = []any{
	(*CredentialsRegisterLinkSendRequest)(nil),     // 0: authpb.CredentialsRegisterLinkSendRequest
	(*CredentialsRegisterLinkSendResponce)(nil),    // 1: authpb.CredentialsRegisterLinkSendResponce
	(*CredentialsRegisterLinkConfirmRequest)(nil),  // 2: authpb.CredentialsRegisterLinkConfirmRequest
	(*CredentialsRegisterLinkConfirmResponce)(nil), // 3: authpb.CredentialsRegisterLinkConfirmResponce
	(*CredentialsLoginRequest)(nil),                // 4: authpb.CredentialsLoginRequest
	(*CredentialsLoginResponce)(nil),               // 5: authpb.CredentialsLoginResponce
	(*TokenRefreshRequest)(nil),                    // 6: authpb.TokenRefreshRequest
	(*TokenRefreshResponce)(nil),                   // 7: authpb.TokenRefreshResponce
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: authpb.AuthService.CredentialsRegisterLinkSend:input_type -> authpb.CredentialsRegisterLinkSendRequest
	2, // 1: authpb.AuthService.CredentialsRegisterLinkConfirm:input_type -> authpb.CredentialsRegisterLinkConfirmRequest
	4, // 2: authpb.AuthService.CredentialsLogin:input_type -> authpb.CredentialsLoginRequest
	6, // 3: authpb.AuthService.TokenRefresh:input_type -> authpb.TokenRefreshRequest
	1, // 4: authpb.AuthService.CredentialsRegisterLinkSend:output_type -> authpb.CredentialsRegisterLinkSendResponce
	3, // 5: authpb.AuthService.CredentialsRegisterLinkConfirm:output_type -> authpb.CredentialsRegisterLinkConfirmResponce
	5, // 6: authpb.AuthService.CredentialsLogin:output_type -> authpb.CredentialsLoginResponce
	7, // 7: authpb.AuthService.TokenRefresh:output_type -> authpb.TokenRefreshResponce
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
